### PR TITLE
readme adaptation

### PR DESCRIPTION
**Pull request by AnneliektH**
Changed readme

### CODE REVIEW

**Comment by ctb** [comment]
Nice work! There was a merge conflict for reasons I don't entirely understand, but I fixed it in db13174

**Comment by ctb** [comment]
so you'll need to do a `git pull` in your local working directory / repo on this.

**Comment by ctb** [comment]
and then check under "Files changed" to see that the diff looks right - I might have made the wrong change when doing the merge.

**Comment by AnneliektH** [comment]
That worked! I will try again this week to do something else, so I can get
used to GitHub.
I do have a specific question about how to add optional variables to the
command line options. Basically, how do i parse an optional variable to a
plugin? Do you have an example plugin that you wrote that does that?

**Pull request merged**
